// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TarkovAssistant.Backend.Database;

#nullable disable

namespace TarkovAssistant.Backend.Database.Migrations
{
    [DbContext(typeof(TarkovAssistantDbContext))]
    [Migration("20260711142315_InitialDomain")]
    partial class InitialDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Ammunition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AccuracyModifier")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("AmmunitionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ArmorDamage")
                        .HasColumnType("integer");

                    b.Property<Guid>("CaliberId")
                        .HasColumnType("uuid");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<decimal>("FragmentationChance")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("HeavyBleedModifier")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("InitialSpeedMetersPerSecond")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<bool>("IsTracer")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LightBleedModifier")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("PenetrationChance")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<int>("PenetrationPower")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PenetrationPowerDeviation")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<int?>("ProjectileCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RecoilModifier")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<decimal>("RicochetChance")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<int>("StackMaximumSize")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StaminaBurnPerDamage")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("TracerColor")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("WeightKilograms")
                        .HasPrecision(10, 5)
                        .HasColumnType("numeric(10,5)");

                    b.HasKey("Id");

                    b.HasIndex("CaliberId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("ammunition", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Caliber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("calibers", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.CatalogVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("catalog_versions", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.HideoutItemRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("HideoutStationLevelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.HasIndex("HideoutStationLevelId", "ItemId")
                        .IsUnique();

                    b.ToTable("hideout_item_requirements", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.HideoutStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TarkovDataId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("hideout_stations", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.HideoutStationLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ConstructionTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("HideoutStationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TarkovDataId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.HasIndex("HideoutStationId", "Level")
                        .IsUnique();

                    b.ToTable("hideout_station_levels", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImportName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ImportedRecordCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ImportName", "StartedAt");

                    b.ToTable("import_runs", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ImportState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ImportName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastAttemptFinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastAttemptStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSucceededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRunId");

                    b.HasIndex("ImportName")
                        .IsUnique();

                    b.ToTable("import_states", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("BasePrice")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("FleaMarketFee")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumFleaLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WeightKilograms")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<string>("WikiUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ItemCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("MinimumFleaLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("item_categories", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ItemCategoryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemId", "CategoryId")
                        .IsUnique();

                    b.ToTable("item_category_assignments", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ItemImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "Kind")
                        .IsUnique();

                    b.ToTable("item_images", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ItemMarketSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Average24HourPrice")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ChangeLast48Hours")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)");

                    b.Property<decimal?>("ChangeLast48HoursPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<int?>("High24HourPrice")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LastLowPrice")
                        .HasColumnType("integer");

                    b.Property<int?>("LastOfferCount")
                        .HasColumnType("integer");

                    b.Property<int?>("Low24HourPrice")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "ObservedAt")
                        .IsUnique();

                    b.ToTable("item_market_snapshots", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ItemPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Price")
                        .HasColumnType("integer");

                    b.Property<int?>("PriceRoubles")
                        .HasColumnType("integer");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.HasIndex("ItemId", "VendorId", "Direction", "ObservedAt")
                        .IsUnique();

                    b.ToTable("item_prices", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "Value")
                        .IsUnique();

                    b.ToTable("item_types", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Magazine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AmmunitionCheckModifier")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Ergonomics")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("LoadModifier")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<decimal?>("MalfunctionChance")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("RecoilModifier")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("magazines", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.MagazineAmmunitionCompatibility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmmunitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MagazineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AmmunitionId");

                    b.HasIndex("MagazineId", "AmmunitionId")
                        .IsUnique();

                    b.ToTable("magazine_ammunition_compatibilities", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("maps", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FactionName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool?>("IsKappaRequired")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLightkeeperRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MapId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MinimumPlayerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WikiUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("TraderId");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.QuestObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaximumDurability")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumDogTagLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumDurability")
                        .HasColumnType("integer");

                    b.Property<bool?>("MustBeFoundInRaid")
                        .HasColumnType("boolean");

                    b.Property<string>("ObjectiveType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RequiredCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("quest_objectives", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.QuestObjectiveItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestObjectiveId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("QuestObjectiveId", "ItemId")
                        .IsUnique();

                    b.ToTable("quest_objective_items", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.QuestObjectiveMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestObjectiveId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("QuestObjectiveId", "MapId")
                        .IsUnique();

                    b.ToTable("quest_objective_maps", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Trader", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrencyItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("HighResolutionImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("ResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TarkovDataId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyItemId");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("traders", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.TraderLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("InsuranceRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<decimal>("PayRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<decimal?>("RepairCostMultiplier")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<int>("RequiredCommerce")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredPlayerLevel")
                        .HasColumnType("integer");

                    b.Property<decimal>("RequiredReputation")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.HasIndex("TraderId", "Level")
                        .IsUnique();

                    b.ToTable("trader_levels", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("ExternalSource", "ExternalId")
                        .IsUnique();

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaliberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultAmmunitionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DefaultErgonomics")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<int?>("DefaultHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultHorizontalRecoil")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultVerticalRecoil")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DefaultWeightKilograms")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int?>("DefaultWidth")
                        .HasColumnType("integer");

                    b.Property<int?>("EffectiveDistanceMeters")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Ergonomics")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<int?>("FireRateRoundsPerMinute")
                        .HasColumnType("integer");

                    b.Property<int?>("HorizontalRecoil")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaximumDurability")
                        .HasColumnType("integer");

                    b.Property<int?>("SightingRangeMeters")
                        .HasColumnType("integer");

                    b.Property<int?>("VerticalRecoil")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaliberId");

                    b.HasIndex("DefaultAmmunitionId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("weapons", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.WeaponAmmunitionCompatibility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmmunitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeaponId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AmmunitionId");

                    b.HasIndex("WeaponId", "AmmunitionId")
                        .IsUnique();

                    b.ToTable("weapon_ammunition_compatibilities", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.WeaponFireMode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WeaponId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeaponId", "Mode")
                        .IsUnique();

                    b.ToTable("weapon_fire_modes", (string)null);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Ammunition", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Caliber", null)
                        .WithMany()
                        .HasForeignKey("CaliberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("TarkovAssistant.Backend.Database.Entities.Ammunition", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.HideoutItemRequirement", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.HideoutStationLevel", null)
                        .WithMany()
                        .HasForeignKey("HideoutStationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.HideoutStationLevel", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.HideoutStation", null)
                        .WithMany()
                        .HasForeignKey("HideoutStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ImportState", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.ImportRun", null)
                        .WithMany()
                        .HasForeignKey("CurrentRunId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ItemCategoryAssignment", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.ItemCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ItemImage", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ItemMarketSnapshot", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ItemPrice", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Vendor", null)
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.ItemType", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Magazine", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("TarkovAssistant.Backend.Database.Entities.Magazine", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.MagazineAmmunitionCompatibility", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Ammunition", null)
                        .WithMany()
                        .HasForeignKey("AmmunitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Magazine", null)
                        .WithMany()
                        .HasForeignKey("MagazineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Quest", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Map", null)
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Trader", null)
                        .WithMany()
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.QuestObjective", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.QuestObjectiveItem", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarkovAssistant.Backend.Database.Entities.QuestObjective", null)
                        .WithMany()
                        .HasForeignKey("QuestObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.QuestObjectiveMap", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Map", null)
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarkovAssistant.Backend.Database.Entities.QuestObjective", null)
                        .WithMany()
                        .HasForeignKey("QuestObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Trader", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("CurrencyItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.TraderLevel", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Trader", null)
                        .WithMany()
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.Weapon", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Caliber", null)
                        .WithMany()
                        .HasForeignKey("CaliberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Ammunition", null)
                        .WithMany()
                        .HasForeignKey("DefaultAmmunitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("TarkovAssistant.Backend.Database.Entities.Weapon", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.WeaponAmmunitionCompatibility", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Ammunition", null)
                        .WithMany()
                        .HasForeignKey("AmmunitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TarkovAssistant.Backend.Database.Entities.WeaponFireMode", b =>
                {
                    b.HasOne("TarkovAssistant.Backend.Database.Entities.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
